2018-05-16 22:19:50,099 - INFO - Bot started
2018-05-16 22:19:50,108 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3cd3dfc438>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAHNZW9uAvHVsrw4yAmreyYkUaHZVEzuAYA/deleteWebhook
2018-05-16 22:19:50,111 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3cd3dfc588>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAHNZW9uAvHVsrw4yAmreyYkUaHZVEzuAYA/deleteWebhook
2018-05-16 22:19:50,114 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3cd3dfcba8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAHNZW9uAvHVsrw4yAmreyYkUaHZVEzuAYA/deleteWebhook
2018-05-16 22:19:50,117 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAHNZW9uAvHVsrw4yAmreyYkUaHZVEzuAYA/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3cd3e121d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:19:50,118 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:32:48,957 - INFO - Bot started
2018-05-16 22:32:49,497 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbb6c50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:32:49,950 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbc4588>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:32:50,407 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbd3a90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:32:50,784 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbd3be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:32:50,784 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:33:00,228 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbb6ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:00,603 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe11d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:00,978 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe1278>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:01,353 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe1438>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:33:01,353 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 22:33:13,026 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe1630>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:13,435 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe19e8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:13,811 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe1a90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:14,188 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe1c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:33:14,188 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
2018-05-16 22:34:11,359 - INFO - Bot started
2018-05-16 22:34:11,792 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e78bc50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:12,168 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7995f8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:12,544 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7a8a90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:12,956 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7a8be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:34:12,956 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:34:20,837 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e78bac8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:21,266 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7b81d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:21,646 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7b8278>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:22,078 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7b8438>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:34:22,078 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 22:38:46,792 - INFO - Bot started
2018-05-16 22:38:47,221 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698a9cf8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:47,597 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698b64a8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:48,004 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698c4978>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:48,482 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698c4c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:38:48,482 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:38:56,430 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698a9b70>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:56,868 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698d4240>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:57,306 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698d42e8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:57,717 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698d44a8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:38:57,717 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 22:40:09,212 - INFO - Bot started
2018-05-16 22:40:55,049 - INFO - Bot started
2018-05-16 22:40:55,479 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa05302d68>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:40:55,891 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0530f668>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:40:56,309 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0531db38>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:40:56,747 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0531dc88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:40:56,748 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:41:04,695 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa05302ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:05,113 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532c278>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:05,524 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532c320>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:05,896 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532c4e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:41:05,897 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 22:41:17,587 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532c0f0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:17,962 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532ca90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:18,337 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532cb38>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:18,714 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532ccf8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:41:18,714 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
2018-05-16 22:45:44,993 - INFO - Bot started
2018-05-16 22:46:15,517 - INFO - Bot started
2018-05-16 22:46:15,523 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe1685f3c8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:15,526 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe1685f518>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:15,529 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe1685fb38>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:15,532 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe16876278>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:46:15,532 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:46:23,043 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe16876400>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:23,047 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe168764a8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:23,050 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe16876550>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:23,053 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe16876630>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:46:23,054 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 22:49:58,390 - INFO - Bot started
2018-05-16 22:49:58,396 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a6126f400>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:49:58,399 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a6126f550>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:49:58,402 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a6126fcc0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:49:58,405 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a612862b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:49:58,405 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:50:05,916 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a61286358>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:50:05,921 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a612864e0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:50:05,925 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a61286588>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:50:05,930 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a61286668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:50:05,930 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 23:05:31,795 - INFO - Bot started
2018-05-16 23:05:32,220 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df5fbcf8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:32,597 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df6086a0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:33,064 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df617b38>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:33,506 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df617c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:05:33,506 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 23:05:41,389 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df5fbb70>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:41,769 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df626278>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:42,141 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df626320>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:42,573 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df6264e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:05:42,573 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 23:25:48,165 - INFO - Bot started
2018-05-16 23:32:40,933 - INFO - Bot started
2018-05-16 23:32:54,027 - INFO - Bot started
2018-05-16 23:33:09,994 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770f76d30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:10,422 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770f836a0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:10,857 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770f8eb70>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:11,232 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770f8eba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:33:11,232 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 23:33:19,151 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770f76ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:19,524 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa02b0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:19,950 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0320>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:20,386 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:33:20,386 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 23:33:32,022 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa05f8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:32,431 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:32,812 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0b38>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:33,221 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0c18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:33:33,222 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
2018-05-16 23:33:50,519 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0908>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:50,892 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:51,329 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0780>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:51,708 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:33:51,708 - WARNING - Failed bootstrap phase; try=4 max_retries=-1
2018-05-16 23:34:15,143 - INFO - Received signal 15 (SIGTERM), stopping...
2018-05-16 23:34:15,143 - INFO - Received signal 15 (SIGTERM), stopping...
2018-05-16 23:34:15,143 - INFO - Received signal 15 (SIGTERM), stopping...
2018-05-16 23:34:15,144 - INFO - Received signal 15 (SIGTERM), stopping...
2018-05-17 20:55:54,763 - INFO - Bot started
2018-05-17 20:55:57,957 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b60cd68>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:01,063 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b60cef0>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:04,157 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b6185c0>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:07,267 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b6249e8>: Failed to establish a new connection: [Errno 113] No route to host',))
2018-05-17 20:56:07,267 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-17 20:56:14,840 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b624c50>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:14,927 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b624e48>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:18,052 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b624eb8>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:21,167 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b637080>: Failed to establish a new connection: [Errno 113] No route to host',))
2018-05-17 20:56:21,167 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-17 20:56:32,458 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b637128>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:32,486 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b637320>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:35,554 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b637390>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:38,656 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b6374a8>: Failed to establish a new connection: [Errno 113] No route to host',))
2018-05-17 20:56:38,656 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
2018-05-24 20:50:12,136 - INFO - Bot started
2018-05-24 20:50:13,971 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40d3ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:50:14,164 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40e16d8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:50:14,357 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40ebba8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:50:14,551 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40ebcf8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 20:50:14,551 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-24 20:50:22,252 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40d3d30>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:50:22,446 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40fd2e8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:50:22,640 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40fd390>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:50:22,833 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40fd550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 20:50:22,833 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-24 20:50:34,282 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40fd128>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:50:34,477 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40fdb00>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:50:34,671 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40fdba8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:50:34,866 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f09b40fdd68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 20:50:34,866 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
2018-05-24 20:53:11,925 - INFO - Bot started
2018-05-24 20:53:12,730 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcb9fd68>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:13,434 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbb9ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:14,134 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbb9b00>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:14,831 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbb9cf8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 20:53:14,831 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-24 20:53:22,531 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcb9fbe0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:22,726 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbca2e8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:22,919 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbca390>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:23,118 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbca550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 20:53:23,118 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-24 20:53:34,562 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbca128>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:34,755 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbcab00>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:34,948 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbcaba8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:35,140 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbcad68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 20:53:35,140 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
2018-05-24 20:53:52,221 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edc145048>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:52,417 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbcac50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:52,610 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbcaba8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:53:52,803 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbcac88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 20:53:52,804 - WARNING - Failed bootstrap phase; try=4 max_retries=-1
2018-05-24 20:54:18,375 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbca8d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:54:18,568 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbca5c0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:54:18,765 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbca6a0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 20:54:18,959 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5edcbca4e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 20:54:18,959 - WARNING - Failed bootstrap phase; try=5 max_retries=-1
2018-05-24 21:08:30,302 - INFO - Bot started
2018-05-24 21:08:58,198 - INFO - Bot started
2018-05-24 21:09:05,621 - INFO - Bot started
2018-05-24 21:09:14,217 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f8fa001be10>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:09:14,422 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f8fa0028748>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:09:26,619 - INFO - Bot started
2018-05-24 21:09:26,916 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1efcc88>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:09:27,165 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1efcef0>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:09:27,413 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1f14b70>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:09:27,661 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1f14d30>: Failed to establish a new connection: SOCKS5 authentication failed',))
2018-05-24 21:09:27,662 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-24 21:09:35,416 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1efcb00>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:09:35,663 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1f263c8>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:09:35,911 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1f26470>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:09:36,158 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1f26668>: Failed to establish a new connection: SOCKS5 authentication failed',))
2018-05-24 21:09:36,159 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-24 21:09:47,663 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1f26080>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:09:47,911 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1f26cc0>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:09:48,158 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1f26d68>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:09:48,405 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1f26f60>: Failed to establish a new connection: SOCKS5 authentication failed',))
2018-05-24 21:09:48,406 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
2018-05-24 21:10:05,530 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa00921d0>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:10:05,780 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa00925f8>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:10:06,029 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1f26d30>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:10:06,276 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3fa1f26f28>: Failed to establish a new connection: SOCKS5 authentication failed',))
2018-05-24 21:10:06,276 - WARNING - Failed bootstrap phase; try=4 max_retries=-1
2018-05-24 21:19:20,521 - INFO - Bot started
2018-05-24 21:19:20,822 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f6be3387d68>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:19:21,071 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f6be33a1908>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:19:21,318 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f6be33a1b38>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:19:21,566 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f6be33a1d68>: Failed to establish a new connection: SOCKS5 authentication failed',))
2018-05-24 21:19:21,566 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-24 21:19:29,828 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f6be3387be0>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:19:30,576 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f6be33b0400>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:19:31,327 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f6be33b04a8>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:19:32,079 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f6be33b06a0>: Failed to establish a new connection: SOCKS5 authentication failed',))
2018-05-24 21:19:32,079 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-24 21:19:43,578 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f6be33b00b8>: Failed to establish a new connection: SOCKS5 authentication failed',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:23:29,606 - INFO - Bot started
2018-05-24 21:23:31,364 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f895588de48>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:23:31,556 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f895588df60>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:23:31,754 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f89558a5c18>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:23:31,948 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f89558a5d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 21:23:31,948 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-24 21:23:39,647 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f895588dc88>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:23:39,841 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f89558b8358>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:23:40,034 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f89558b8400>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:23:40,227 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f89558b85c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 21:23:40,228 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-24 21:33:01,006 - INFO - Bot started
2018-05-24 21:33:09,958 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db63b38>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:33:10,151 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db7db00>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:33:10,346 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db7dbe0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:33:10,540 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db7de10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 21:33:10,540 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-24 21:33:18,238 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db8d048>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:33:18,433 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db8d3c8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:33:18,627 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db8d470>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:33:18,828 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db8d668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 21:33:18,829 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-24 21:33:30,278 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db8d240>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:33:30,473 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db8dbe0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:33:30,668 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db8dc88>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook
2018-05-24 21:33:30,862 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAEj31z09FQR5SwEiDbEvyIfVcP5jUWh3sc/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe32db8de80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-24 21:33:30,862 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
