2018-05-16 22:19:50,099 - INFO - Bot started
2018-05-16 22:19:50,108 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3cd3dfc438>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAHNZW9uAvHVsrw4yAmreyYkUaHZVEzuAYA/deleteWebhook
2018-05-16 22:19:50,111 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3cd3dfc588>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAHNZW9uAvHVsrw4yAmreyYkUaHZVEzuAYA/deleteWebhook
2018-05-16 22:19:50,114 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3cd3dfcba8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAHNZW9uAvHVsrw4yAmreyYkUaHZVEzuAYA/deleteWebhook
2018-05-16 22:19:50,117 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAHNZW9uAvHVsrw4yAmreyYkUaHZVEzuAYA/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3cd3e121d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:19:50,118 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:32:48,957 - INFO - Bot started
2018-05-16 22:32:49,497 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbb6c50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:32:49,950 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbc4588>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:32:50,407 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbd3a90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:32:50,784 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbd3be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:32:50,784 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:33:00,228 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbb6ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:00,603 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe11d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:00,978 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe1278>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:01,353 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe1438>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:33:01,353 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 22:33:13,026 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe1630>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:13,435 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe19e8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:13,811 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe1a90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook
2018-05-16 22:33:14,188 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot584444640:AAHZr60EYxxIWobrFPEYWRUV8RsfHonjtJQ/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7efc6cbe1c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:33:14,188 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
2018-05-16 22:34:11,359 - INFO - Bot started
2018-05-16 22:34:11,792 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e78bc50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:12,168 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7995f8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:12,544 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7a8a90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:12,956 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7a8be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:34:12,956 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:34:20,837 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e78bac8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:21,266 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7b81d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:21,646 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7b8278>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:34:22,078 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f926e7b8438>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:34:22,078 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 22:38:46,792 - INFO - Bot started
2018-05-16 22:38:47,221 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698a9cf8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:47,597 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698b64a8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:48,004 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698c4978>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:48,482 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698c4c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:38:48,482 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:38:56,430 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698a9b70>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:56,868 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698d4240>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:57,306 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698d42e8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:38:57,717 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fd0698d44a8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:38:57,717 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 22:40:09,212 - INFO - Bot started
2018-05-16 22:40:55,049 - INFO - Bot started
2018-05-16 22:40:55,479 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa05302d68>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:40:55,891 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0530f668>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:40:56,309 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0531db38>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:40:56,747 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0531dc88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:40:56,748 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:41:04,695 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa05302ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:05,113 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532c278>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:05,524 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532c320>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:05,896 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532c4e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:41:05,897 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 22:41:17,587 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532c0f0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:17,962 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532ca90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:18,337 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532cb38>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:41:18,714 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ffa0532ccf8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:41:18,714 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
2018-05-16 22:45:44,993 - INFO - Bot started
2018-05-16 22:46:15,517 - INFO - Bot started
2018-05-16 22:46:15,523 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe1685f3c8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:15,526 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe1685f518>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:15,529 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe1685fb38>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:15,532 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe16876278>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:46:15,532 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:46:23,043 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe16876400>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:23,047 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe168764a8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:23,050 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe16876550>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:46:23,053 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe16876630>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:46:23,054 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 22:49:58,390 - INFO - Bot started
2018-05-16 22:49:58,396 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a6126f400>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:49:58,399 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a6126f550>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:49:58,402 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a6126fcc0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:49:58,405 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a612862b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:49:58,405 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 22:50:05,916 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a61286358>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:50:05,921 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a612864e0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:50:05,925 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a61286588>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 22:50:05,930 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a61286668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 22:50:05,930 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 23:05:31,795 - INFO - Bot started
2018-05-16 23:05:32,220 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df5fbcf8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:32,597 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df6086a0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:33,064 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df617b38>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:33,506 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df617c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:05:33,506 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 23:05:41,389 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df5fbb70>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:41,769 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df626278>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:42,141 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df626320>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:05:42,573 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe6df6264e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:05:42,573 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 23:25:48,165 - INFO - Bot started
2018-05-16 23:32:40,933 - INFO - Bot started
2018-05-16 23:32:54,027 - INFO - Bot started
2018-05-16 23:33:09,994 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770f76d30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:10,422 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770f836a0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:10,857 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770f8eb70>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:11,232 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770f8eba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:33:11,232 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-16 23:33:19,151 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770f76ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:19,524 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa02b0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:19,950 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0320>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:20,386 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:33:20,386 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-16 23:33:32,022 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa05f8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:32,431 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:32,812 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0b38>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:33,221 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0c18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:33:33,222 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
2018-05-16 23:33:50,519 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0908>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:50,892 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:51,329 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0780>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-16 23:33:51,708 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f0770fa0e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-16 23:33:51,708 - WARNING - Failed bootstrap phase; try=4 max_retries=-1
2018-05-16 23:34:15,143 - INFO - Received signal 15 (SIGTERM), stopping...
2018-05-16 23:34:15,143 - INFO - Received signal 15 (SIGTERM), stopping...
2018-05-16 23:34:15,143 - INFO - Received signal 15 (SIGTERM), stopping...
2018-05-16 23:34:15,144 - INFO - Received signal 15 (SIGTERM), stopping...
2018-05-17 20:55:54,763 - INFO - Bot started
2018-05-17 20:55:57,957 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b60cd68>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:01,063 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b60cef0>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:04,157 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b6185c0>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:07,267 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b6249e8>: Failed to establish a new connection: [Errno 113] No route to host',))
2018-05-17 20:56:07,267 - WARNING - Failed bootstrap phase; try=1 max_retries=-1
2018-05-17 20:56:14,840 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b624c50>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:14,927 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b624e48>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:18,052 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b624eb8>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:21,167 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b637080>: Failed to establish a new connection: [Errno 113] No route to host',))
2018-05-17 20:56:21,167 - WARNING - Failed bootstrap phase; try=2 max_retries=-1
2018-05-17 20:56:32,458 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b637128>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:32,486 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b637320>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:35,554 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b637390>: Failed to establish a new connection: [Errno 113] No route to host',)': /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook
2018-05-17 20:56:38,656 - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot561255866:AAG_NKHXCkLDMvBQ0vJHOBi2-OP_LLZ53Vg/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f3b0b6374a8>: Failed to establish a new connection: [Errno 113] No route to host',))
2018-05-17 20:56:38,656 - WARNING - Failed bootstrap phase; try=3 max_retries=-1
